# =============================================================================
# docker-compose.yaml
#
# Runs the full RMF backend stack HEADLESS: rmf-sim (fleet adapter + Gazebo
# server + schedule visualizer), zenoh-router, api-server, and rmf-web.
#
# See notes in README.md
#
# Images maintained by Nexsoss (https://github.com/nexsoss).
# Underlying software © Open Robotics 
# =============================================================================

# build-only dependency
services:
  rmf-base:
    build:
      context: .
      dockerfile: docker/Dockerfile.rmf
      args:
        ROS_DISTRO: lyrical
    image: localhost/open-rmf:lyrical

# rmf with simulation
  rmf-sim:
    build:
      context: .
      dockerfile: docker/Dockerfile.rmf-sim
      args:
        ROS_DISTRO: lyrical
        RMF_IMAGE: localhost/open-rmf:lyrical
    image: localhost/open-rmf:lyrical_sim
    container_name: rmf-sim
    environment:
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
    network_mode: host
    volumes:
      - shared_data:/home/ws_rmf/install/rmf_demos_maps/share/rmf_demos_maps/maps
    command: >
      bash -c "source /home/ws_rmf/install/setup.bash &&
      ros2 launch rmf_demos_gz ${WORLD:-office}.launch.xml headless:=1
      server_uri:=ws://localhost:8000/_internal"
    restart: unless-stopped
    depends_on:
      rmf-api-server:
        condition: service_started
      zenoh-router:
        condition: service_healthy

# zenoh router
  zenoh-router:
    image: eclipse/zenoh:1.9.0-47-g55263c9da
    container_name: zenoh-router
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "7447"]
      interval: 10s
      timeout: 5s
      retries: 5

# rmf api server
  rmf-api-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.rmf-api-server
      args:
        ROS_DISTRO: lyrical
        RMF_IMAGE: localhost/open-rmf:lyrical
    image: localhost/open-rmf:lyrical_api-server
    container_name: rmf-api-server
    environment:
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
    depends_on:
      zenoh-router:
        condition: service_healthy
    network_mode: host
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# rmf web dashboard
  rmf-web-dashboard:
    build:
      context: ./docker
      dockerfile: Dockerfile.rmf-web-dashboard
    image: localhost/open-rmf:lyrical_web-dashboard
    container_name: rmf-web-dashboard
    depends_on:
      rmf-api-server:
        condition: service_started
      zenoh-router:
        condition: service_healthy
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  shared_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/maps